# Generated by Django 5.1.7 on 2025-04-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='donors',
            field=models.ManyToManyField(blank=True, related_name='user_donations', to='users.userprofile'),
        ),
    ]
